# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Curating Menus
email: curatingmenus@gmail.com
description: >
  A mini-site about digital humanities research on historic menus.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.curatingmenus.org" # the base hostname & protocol for your site
twitter_username: curatingmenus
github_username:  public-fare
s3: "https://s3.amazonaws.com/curatingmenus/"

# Build settings
markdown: kramdown
permalink: /articles/:title/
exclude: [src, node_modules, webpack.dev.config.js, webpack.prod.config.js, package.json]
keep_files: [static]
production: true
